---
name: File-Glob-Windows
version: 0.1.2
author:
  - 'tateisu <tateisu@gmail.com>'
abstract: glob routine for Windows environment.
license: perl
requires:
  Test::More: 0
  version: 0
provides:
  File::Glob::Windows:
    file: lib/File/Glob/Windows.pm
    version: 0.1.2
generated_by: Module::Build version 0.26
